Scorecard/Controllers/ScorecardTemplateController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Scorecard.Models;
using System.Data.Entity.Validation;

namespace Scorecard.Controllers
{
    public class ScorecardTemplateController : Controller
    {
        private HovisDWEntities db = new HovisDWEntities();

        // GET: /ScorecardTemplate/
        [Authorize(Roles = "canEditMasterData")]
        public ActionResult Index()
        {
            var t_scorecard_master_template = db.t_Scorecard_Master_Template.Include(t => t.t_Scorecard_Master_Categories).Include(t => t.t_Scorecard_Minor_Categories).Include(t => t.v_PTLStaff_MasterData_Plants);
            return View(t_scorecard_master_template.ToList()
                .OrderByDescending(c => c.SiteCode)
                .ThenByDescending(c => c.MinorCatID));
        }

        // GET: /ScorecardTemplate/ - this provides the measures
        [Authorize(Roles = "canEdit")]
        public ActionResult IndexSubmit()
        {
            string UserIdentity = User.Identity.Name;
            string DefaultSite = "No Default Site";
            string ToDaysDate = DateTime.Now.ToString("yyyyMMdd");
            string FinYear = "";
            string FinWeek = "";


            // Set the user name first
            if (UserIdentity == "")
            {
                UserIdentity = "Not Logged in";
            }

            // Get the default site for the user
            IQueryable<t_Scorecard_Master_UserSites> userSites = db.t_Scorecard_Master_UserSites
                .Where(c => c.UserName == UserIdentity);
            userSites = userSites.Take(1);
            foreach (var DefaultSites in userSites)
            {
                DefaultSite = Convert.ToString(DefaultSites.UserSiteCode);
            }

            // get the financial week and year
            IQueryable<v_Hovis_Calendar> fincalendars = db.v_Hovis_Calendar
                .Where(c => c.CalendarDateChar == ToDaysDate);
            fincalendars = fincalendars.Take(1);
            foreach (var WeekYears in fincalendars)
            {
                FinWeek = Convert.ToString(WeekYears.FinancialWeek);
                FinYear = Convert.ToString(WeekYears.FinancialYear);
            }

            ViewBag.UserIdentity = UserIdentity;
            ViewBag.DefaultSite = DefaultSite;
            ViewBag.FinWeek = FinWeek;
            ViewBag.FinYear = FinYear;

            //var sites = db.v_PTLStaff_MasterData_Plants.OrderBy(q => q.PlantDesc).ToList();
            //ViewBag.SelectedSite = new SelectList(sites, "Plant", "PlantDesc", SelectedSite);
            //int SiteID = SelectedSite.GetValueOrDefault();
            //string SiteIDchar = Convert.ToString(SiteID);

            string SiteIDchar = DefaultSite;

            IQueryable<t_Scorecard_Master_Template> t_scorecard_master_templates = db.t_Scorecard_Master_Template
                .Where(c => c.SiteCode == SiteIDchar)
                .Include(t => t.t_Scorecard_Master_Categories).Include(t => t.t_Scorecard_Minor_Categories).Include(t => t.v_PTLStaff_MasterData_Plants);
            var sql = t_scorecard_master_templates.ToString();
            return View(t_scorecard_master_templates.ToList());


                //.Where(c => !SelectedSite.HasValue || Convert.ToInt32(c.SiteCode) == SiteID)

            //var t_scorecard_master_template = db.t_Scorecard_Master_Template.Include(t => t.t_Scorecard_Master_Categories).Include(t => t.t_Scorecard_Minor_Categories).Include(t => t.v_PTLStaff_MasterData_Plants);
            //return View(t_scorecard_master_template.ToList());
        }

        // GET: /ScorecardTemplate/Details/5
        [Authorize(Roles = "canEditMasterData")]
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            t_Scorecard_Master_Template t_scorecard_master_template = db.t_Scorecard_Master_Template.Find(id);
            if (t_scorecard_master_template == null)
            {
                return HttpNotFound();
            }
            return View(t_scorecard_master_template);
        }

        // GET: /ScorecardTemplate/Create
        [Authorize(Roles = "canEditMasterData")]
        public ActionResult Create()
        {
            ViewBag.MasterCatID = new SelectList(db.t_Scorecard_Master_Categories, "ID", "MasterCatCode");
            ViewBag.MinorCatID = new SelectList(db.t_Scorecard_Minor_Categories, "ID", "MinorCatCode");
            ViewBag.SiteCode = new SelectList(db.v_PTLStaff_MasterData_Plants, "Plant", "PlantDesc");
            return View();
        }

        // POST: /ScorecardTemplate/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "canEditMasterData")]
        public ActionResult Create([Bind(Include = "Recid,SiteCode,MasterCatID,MinorCatID,Actual,Target,Comments,LastChangedBy,LastChangedDate,Confirmed")] t_Scorecard_Master_Template t_scorecard_master_template)
        {
            if (ModelState.IsValid)
            {
                db.t_Scorecard_Master_Template.Add(t_scorecard_master_template);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MasterCatID = new SelectList(db.t_Scorecard_Master_Categories, "ID", "MasterCatCode", t_scorecard_master_template.MasterCatID);
            ViewBag.MinorCatID = new SelectList(db.t_Scorecard_Minor_Categories, "ID", "MinorCatCode", t_scorecard_master_template.MinorCatID);
            ViewBag.SiteCode = new SelectList(db.v_PTLStaff_MasterData_Plants, "Plant", "PlantDesc", t_scorecard_master_template.SiteCode);
            return View(t_scorecard_master_template);
        }

        // GET: /ScorecardTemplate/Edit/5
        [Authorize(Roles = "canEditMasterData")]
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            t_Scorecard_Master_Template t_scorecard_master_template = db.t_Scorecard_Master_Template.Find(id);
            if (t_scorecard_master_template == null)
            {
                return HttpNotFound();
            }
            ViewBag.MasterCatID = new SelectList(db.t_Scorecard_Master_Categories, "ID", "MasterCatCode", t_scorecard_master_template.MasterCatID);
            ViewBag.MinorCatID = new SelectList(db.t_Scorecard_Minor_Categories, "ID", "MinorCatCode", t_scorecard_master_template.MinorCatID);
            ViewBag.SiteCode = new SelectList(db.v_PTLStaff_MasterData_Plants, "Plant", "PlantDesc", t_scorecard_master_template.SiteCode);
            return View(t_scorecard_master_template);
        }

        // POST: /ScorecardTemplate/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "canEditMasterData")]
        public ActionResult Edit([Bind(Include = "Recid,SiteCode,MasterCatID,MinorCatID,Actual,Target,Comments,LastChangedBy,LastChangedDate,Confirmed")] t_Scorecard_Master_Template t_scorecard_master_template)
        {
            if (ModelState.IsValid)
            {
                t_scorecard_master_template.LastChangedBy = User.Identity.Name;
                t_scorecard_master_template.LastChangedDate = DateTime.Now;
                db.Entry(t_scorecard_master_template).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MasterCatID = new SelectList(db.t_Scorecard_Master_Categories, "ID", "MasterCatCode", t_scorecard_master_template.MasterCatID);
            ViewBag.MinorCatID = new SelectList(db.t_Scorecard_Minor_Categories, "ID", "MinorCatCode", t_scorecard_master_template.MinorCatID);
            ViewBag.SiteCode = new SelectList(db.v_PTLStaff_MasterData_Plants, "Plant", "PlantDesc", t_scorecard_master_template.SiteCode);
            return View(t_scorecard_master_template);
        }

        // GET: /ScorecardTemplate/Edit/5 - change measures
        [Authorize(Roles = "canEdit")]
        public ActionResult EditSubmit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            t_Scorecard_Master_Template t_scorecard_master_template = db.t_Scorecard_Master_Template.Find(id);
            if (t_scorecard_master_template == null)
            {
                return HttpNotFound();
            }
            ViewBag.MasterCatID = new SelectList(db.t_Scorecard_Master_Categories, "ID", "MasterCatCode", t_scorecard_master_template.MasterCatID);
            ViewBag.MinorCatID = new SelectList(db.t_Scorecard_Minor_Categories, "ID", "MinorCatCode", t_scorecard_master_template.MinorCatID);
            ViewBag.SiteCode = new SelectList(db.v_PTLStaff_MasterData_Plants, "Plant", "PlantDesc", t_scorecard_master_template.SiteCode);
            return View(t_scorecard_master_template);
        }

        // POST: /ScorecardTemplate/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "canEdit")]

Scorecard/Views/ScorecardTemplate/Create.cshtml
@model Scorecard.Models.t_Scorecard_Master_Template

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>New measure</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.SiteCode, "SiteCode", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SiteCode", String.Empty)
                @Html.ValidationMessageFor(model => model.SiteCode)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MasterCatID, "MasterCatID", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MasterCatID", String.Empty)
                @Html.ValidationMessageFor(model => model.MasterCatID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MinorCatID, "MinorCatID", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MinorCatID", String.Empty)
                @Html.ValidationMessageFor(model => model.MinorCatID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Actual, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Actual)
                @Html.ValidationMessageFor(model => model.Actual)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Target, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Target)
                @Html.ValidationMessageFor(model => model.Target)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Scorecard/Views/ScorecardTemplate/Delete.cshtml
@model Scorecard.Models.t_Scorecard_Master_Template

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>No further posts will be possible for this measure</h4>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.v_PTLStaff_MasterData_Plants.PlantDesc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.v_PTLStaff_MasterData_Plants.PlantDesc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.t_Scorecard_Master_Categories.MasterCatCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.t_Scorecard_Master_Categories.MasterCatCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.t_Scorecard_Minor_Categories.MinorCatCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.t_Scorecard_Minor_Categories.MinorCatCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Actual)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Actual)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Target)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Target)
            @Html.HiddenFor(model => model.Comments)
            @Html.HiddenFor(model => model.LastChangedBy)
            @Html.HiddenFor(model => model.LastChangedDate)
            @Html.HiddenFor(model => model.Confirmed)
        </dd>






    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Scorecard/Views/ScorecardTemplate/Details.cshtml
@model Scorecard.Models.t_Scorecard_Master_Template

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4></h4>
	<hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.v_PTLStaff_MasterData_Plants.PlantDesc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.v_PTLStaff_MasterData_Plants.PlantDesc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.t_Scorecard_Master_Categories.MasterCatCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.t_Scorecard_Master_Categories.MasterCatCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.t_Scorecard_Minor_Categories.MinorCatCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.t_Scorecard_Minor_Categories.MinorCatCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Actual)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Actual)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Target)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Target)
            @Html.HiddenFor(model => model.Comments)
            @Html.HiddenFor(model => model.LastChangedBy)
            @Html.HiddenFor(model => model.LastChangedDate)
            @Html.HiddenFor(model => model.Confirmed)
        </dd>


    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Recid }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Scorecard/Views/ScorecardTemplate/Edit.cshtml
@model Scorecard.Models.t_Scorecard_Master_Template

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4></h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Recid)
        @Html.HiddenFor(model => model.Comments)
        @Html.HiddenFor(model => model.LastChangedBy)
        @Html.HiddenFor(model => model.LastChangedDate)
        @Html.HiddenFor(model => model.Confirmed)


        <div class="form-group">
            @Html.LabelFor(model => model.SiteCode, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SiteCode", String.Empty)
                @Html.ValidationMessageFor(model => model.SiteCode)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MasterCatID, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MasterCatID", String.Empty)
                @Html.ValidationMessageFor(model => model.MasterCatID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MinorCatID, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MinorCatID", String.Empty)
                @Html.ValidationMessageFor(model => model.MinorCatID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Actual, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Actual)
                @Html.ValidationMessageFor(model => model.Actual)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Target, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Target)
                @Html.ValidationMessageFor(model => model.Target)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Scorecard/Views/ScorecardTemplate/EditSubmit.cshtml
@model Scorecard.Models.t_Scorecard_Master_Template

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4></h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Recid)
        @Html.HiddenFor(model => model.SiteCode)
        @Html.HiddenFor(model => model.MasterCatID)
        @Html.HiddenFor(model => model.MinorCatID)
        @Html.HiddenFor(model => model.LastChangedBy)
        @Html.HiddenFor(model => model.LastChangedDate)
        @Html.HiddenFor(model => model.Confirmed)
        @Html.HiddenFor(model => model.Target)




        <div class="form-group">
            @Html.LabelFor(model => model.SiteCode, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.v_PTLStaff_MasterData_Plants.PlantDesc)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MasterCatID, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.t_Scorecard_Master_Categories.MasterCatCode)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MinorCatID, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.t_Scorecard_Minor_Categories.MinorCatCode)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Target, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.Target)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Actual, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Actual)
                @Html.ValidationMessageFor(model => model.Actual)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Comments, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Comments)
                @Html.ValidationMessageFor(model => model.Comments)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "IndexSubmit")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Scorecard/Views/ScorecardTemplate/Index.cshtml
@model IEnumerable<Scorecard.Models.t_Scorecard_Master_Template>

@{
    ViewBag.Title = "Index";
}

<h2>Set up the Scorecard Template</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.v_PTLStaff_MasterData_Plants.PlantDesc)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.t_Scorecard_Master_Categories.MasterCatCode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.t_Scorecard_Minor_Categories.MinorCatCode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Actual)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Target)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.v_PTLStaff_MasterData_Plants.PlantDesc)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.t_Scorecard_Master_Categories.MasterCatCode)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.t_Scorecard_Minor_Categories.MinorCatCode)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Actual)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Target)
            @Html.HiddenFor(modelItem => item.Comments)
            @Html.HiddenFor(modelItem => item.LastChangedBy)
            @Html.HiddenFor(modelItem => item.LastChangedDate)
            @Html.HiddenFor(modelItem => item.Confirmed)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Recid }) |
            @Html.ActionLink("Details", "Details", new { id=item.Recid }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Recid })
        </td>
    </tr>
}

</table>

Scorecard/Views/ScorecardTemplate/IndexSubmit.cshtml
@model IEnumerable<Scorecard.Models.t_Scorecard_Master_Template>

@{
    ViewBag.Title = "Enter results";
}

<h2>Record Results</h2>

@using (Html.BeginForm("DataSubmit", "ScorecardTemplate", FormMethod.Post, new { id = "DataSubmit" }))
{
    <div class="container">
        <div class="row">
            <div class="col-md-offset-1 col-md-2">
                <p> User identity:</p>
            </div>
            <div class="col-md-3">
                @Html.TextBox("UserIdentity", ViewBag.UserIdentity as string)
            </div>
            <div class="col-md-offset-1 col-md-2">
                <p> Financial Year:</p>
            </div>
            <div class="col-md-3">
                @Html.TextBox("FinYear", ViewBag.FinYear as string)
            </div>
         </div>
        <div class="row">
            <div class="col-md-offset-1 col-md-2">
                <p> User Default site:</p>
            </div>
            <div class="col-md-3">
                @Html.TextBox("DefaultSite", ViewBag.DefaultSite as string)
            </div>
            <div class="col-md-offset-1 col-md-2">
                <p> Financial Week :</p>
            </div>
            <div class="col-md-3">
                @Html.TextBox("FinWeek", ViewBag.FinWeek as string)
            </div>
        </div>
    </div>
        <div class="form-group">
            <div class="col-md-offset-1 col-md-11">
                <input type="submit" value="Submit" class="btn btn-primary" />
            </div>
        </div>
}


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.v_PTLStaff_MasterData_Plants.PlantDesc)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.t_Scorecard_Master_Categories.MasterCatCode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.t_Scorecard_Minor_Categories.MinorCatCode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Actual)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Target)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Comments)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.v_PTLStaff_MasterData_Plants.PlantDesc)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.t_Scorecard_Master_Categories.MasterCatCode)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.t_Scorecard_Minor_Categories.MinorCatCode)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Actual)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Target)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Comments)
                @Html.HiddenFor(modelItem => item.LastChangedBy)
                @Html.HiddenFor(modelItem => item.LastChangedDate)
                @Html.HiddenFor(modelItem => item.Confirmed)
            </td>
            <td>
                @Html.ActionLink("Edit", "EditSubmit", new { id = item.Recid })
                @*@Html.ActionLink("Details", "Details", new { id=item.Recid }) |
                    @Html.ActionLink("Delete", "Delete", new { id=item.Recid })*@
            </td>
        </tr>
    }

</table>